return {
		Captains = {
			["Captain II"] = 0,
			["Captain III"] = 0,
			["Captain IV"] = 0,
			["Captain V"] = 0,
			["Captain VI"] = 0,
			["Captain VII"] = 0,
			["Captain VIII"] = 0,
			["Captain IX"] = 0,
			["Captain X"] = 0,
			["Captain XI"] = 0,
			["Captain XII"] = 0,
			["Captain XIII"] = 0,
		},
		Lieutenants = {
			["Lieutenant II"] = 0,
			["Lieutenant III"] = 0,
			["Lieutenant IV"] = 0,
			["Lieutenant V"] = 0,
			["Lieutenant VI"] = 0,
			["Lieutenant VII"] = 0,
			["Lieutenant VIII"] = 0,
			["Lieutenant IX"] = 0,
			["Lieutenant X"] = 0,
			["Lieutenant XI"] = 0,
			["Lieutenant XII"] = 0,
			["Lieutenant XIII"] = 0,
		},
		Fraccions = {
			["Fraccion I"] = {},
			["Fraccion II"] = {},
			["Fraccion III"] = {},
			["Fraccion IV"] = {},
			["Fraccion V"] = {},
			["Fraccion VI"] = {},
			["Fraccion VII"] = {},
			["Fraccion VIII"] = {},
			["Fraccion IX"] = {},
			["Fraccion X"] = {},
		},
		Espadas = {
			["Espada I"] = 0,
			["Espada II"] = 0,
			["Espada III"] = 0,
			["Espada IV"] = 0,
			["Espada V"] = 0,
			["Espada VI"] = 0,
			["Espada VII"] = 0,
			["Espada VIII"] = 0,
			["Espada IX"] = 0,
			["Espada X"] = 0,
		},
		["Heads"] = {
			["Head Espada"] = 0,
			["Head Captain"] = 0,
			["Quincy Emperor"] = 0,
		},
		["Soul King"] = game.CreatorId,
	}
